version: '3.4'

services:
  herogi.leaderboard.api:
    hostname: leaderboardapi
    image: ${DOCKER_REGISTRY-}herogileaderboard
    build:
      context: .
      dockerfile: Herogi.Leaderboard.Api/Dockerfile
    links:
      - "mongo:mongo"
    ports:
      - "2121:2122"

  mongo:
    image: mongo
    hostname: mongo
    volumes:
      - data:/data/db
    environment:
      -  'MONGODB_USER=user' 
      -  'MONGODB_PASS=password!'
    ports:
      - "27017:27017"
    command: mongod --smallfiles
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

  mongo-express:
    image: mongo-express
    hostname: mongo-express
    links:
      - "mongo:mongo"
    ports:
      - "8081:8081"
    environment:
      - 'ME_CONFIG_OPTIONS_EDITORTHEME=ambiance'
      - 'ME_CONFIG_BASICAUTH_USERNAME=user'
      - 'ME_CONFIG_BASICAUTH_PASSWORD=password!'

volumes:
  mongodb:
  mongodb_config: